### ISSUE TITLE
Not able to solve the ( No module named '_curses' )

### ISSUE THREAD

**Issue by Ananya-0306** [DipanshKhandelwal/dev-swiper#1]
Hi Dipansh, Ananya here, I was try to run you #dev-swiper code but iam getting an error- ( No module named '_curses' ) can you please help me out.?!
![Screenshot (279)](https://user-images.githubusercontent.com/74227338/111061798-14f8a880-84cb-11eb-8923-cab303eea0e7.png)

**Comment by DipanshKhandelwal** [comment]
Looks like a windows specific issue. Can you try installing `curses` using : `pip install windows-curses` ?
